package com.citi.group2.simpletps.mapper;

import com.citi.group2.simpletps.entity.salesLeg;
import com.citi.group2.simpletps.entity.salesLegKey;

public interface salesLegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(salesLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int insert(salesLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int insertSelective(salesLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    salesLeg selectByPrimaryKey(salesLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(salesLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(salesLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(salesLeg record);
}