package com.citi.group2.simpletps.mapper;

import com.citi.group2.simpletps.entity.traderLeg;
import com.citi.group2.simpletps.entity.traderLegKey;

public interface traderLegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(traderLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int insert(traderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int insertSelective(traderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    traderLeg selectByPrimaryKey(traderLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(traderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(traderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(traderLeg record);
}