package com.citi.group2.simpletps.mapper;

import com.citi.group2.simpletps.entity.TraderLeg;
import com.citi.group2.simpletps.entity.TraderLegKey;

public interface TraderLegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TraderLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int insert(TraderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int insertSelective(TraderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    TraderLeg selectByPrimaryKey(TraderLegKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TraderLeg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader_leg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraderLeg record);
}