package com.citi.group2.simpletps.mapper;

import com.citi.group2.simpletps.entity.trader;

public interface traderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int insert(trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int insertSelective(trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    trader selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(trader record);
}