package com.citi.group2.simpletps.mapper;

import com.citi.group2.simpletps.entity.Trader;

public interface TraderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int insert(Trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int insertSelective(Trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    Trader selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trader
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trader record);
}