package com.citi.group2.simpletps.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cusip
     *
     * @mbggenerated
     */
    private String cusip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.face_value
     *
     * @mbggenerated
     */
    private Integer faceValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.coupon
     *
     * @mbggenerated
     */
    private BigDecimal coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remaining
     *
     * @mbggenerated
     */
    private Long remaining;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.maturity
     *
     * @mbggenerated
     */
    private Date maturity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cusip
     *
     * @return the value of product.cusip
     *
     * @mbggenerated
     */
    public String getCusip() {
        return cusip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cusip
     *
     * @param cusip the value for product.cusip
     *
     * @mbggenerated
     */
    public void setCusip(String cusip) {
        this.cusip = cusip == null ? null : cusip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.face_value
     *
     * @return the value of product.face_value
     *
     * @mbggenerated
     */
    public Integer getFaceValue() {
        return faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.face_value
     *
     * @param faceValue the value for product.face_value
     *
     * @mbggenerated
     */
    public void setFaceValue(Integer faceValue) {
        this.faceValue = faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.coupon
     *
     * @return the value of product.coupon
     *
     * @mbggenerated
     */
    public BigDecimal getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.coupon
     *
     * @param coupon the value for product.coupon
     *
     * @mbggenerated
     */
    public void setCoupon(BigDecimal coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remaining
     *
     * @return the value of product.remaining
     *
     * @mbggenerated
     */
    public Long getRemaining() {
        return remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remaining
     *
     * @param remaining the value for product.remaining
     *
     * @mbggenerated
     */
    public void setRemaining(Long remaining) {
        this.remaining = remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.maturity
     *
     * @return the value of product.maturity
     *
     * @mbggenerated
     */
    public Date getMaturity() {
        return maturity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.maturity
     *
     * @param maturity the value for product.maturity
     *
     * @mbggenerated
     */
    public void setMaturity(Date maturity) {
        this.maturity = maturity;
    }
}