package com.citi.group2.simpletps.entity;

public class SalesLegKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leg.inter_id
     *
     * @mbggenerated
     */
    private String interId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_leg.txn_id
     *
     * @mbggenerated
     */
    private Integer txnId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leg.inter_id
     *
     * @return the value of sales_leg.inter_id
     *
     * @mbggenerated
     */
    public String getInterId() {
        return interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leg.inter_id
     *
     * @param interId the value for sales_leg.inter_id
     *
     * @mbggenerated
     */
    public void setInterId(String interId) {
        this.interId = interId == null ? null : interId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_leg.txn_id
     *
     * @return the value of sales_leg.txn_id
     *
     * @mbggenerated
     */
    public Integer getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_leg.txn_id
     *
     * @param txnId the value for sales_leg.txn_id
     *
     * @mbggenerated
     */
    public void setTxnId(Integer txnId) {
        this.txnId = txnId;
    }
}