package com.citi.group2.simpletps.entity;

public class seller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_name
     *
     * @mbggenerated
     */
    private String sName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_id
     *
     * @return the value of seller.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_id
     *
     * @param sId the value for seller.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_name
     *
     * @return the value of seller.s_name
     *
     * @mbggenerated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_name
     *
     * @param sName the value for seller.s_name
     *
     * @mbggenerated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }
}