package com.citi.group2.simpletps.entity;

public class trader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader.t_name
     *
     * @mbggenerated
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader.t_account
     *
     * @mbggenerated
     */
    private String tAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader.t_pwd
     *
     * @mbggenerated
     */
    private String tPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader.t_id
     *
     * @return the value of trader.t_id
     *
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader.t_id
     *
     * @param tId the value for trader.t_id
     *
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader.t_name
     *
     * @return the value of trader.t_name
     *
     * @mbggenerated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader.t_name
     *
     * @param tName the value for trader.t_name
     *
     * @mbggenerated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader.t_account
     *
     * @return the value of trader.t_account
     *
     * @mbggenerated
     */
    public String gettAccount() {
        return tAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader.t_account
     *
     * @param tAccount the value for trader.t_account
     *
     * @mbggenerated
     */
    public void settAccount(String tAccount) {
        this.tAccount = tAccount == null ? null : tAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader.t_pwd
     *
     * @return the value of trader.t_pwd
     *
     * @mbggenerated
     */
    public String gettPwd() {
        return tPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader.t_pwd
     *
     * @param tPwd the value for trader.t_pwd
     *
     * @mbggenerated
     */
    public void settPwd(String tPwd) {
        this.tPwd = tPwd == null ? null : tPwd.trim();
    }
}