package com.citi.group2.simpletps.entity;

import java.math.BigDecimal;

public class traderLeg extends traderLegKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.inter_v_num
     *
     * @mbggenerated
     */
    private Integer interVNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.reject_code
     *
     * @mbggenerated
     */
    private String rejectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.t_id
     *
     * @mbggenerated
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.cusip
     *
     * @mbggenerated
     */
    private String cusip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.notional_amount
     *
     * @mbggenerated
     */
    private Integer notionalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.matched_seller_leg
     *
     * @mbggenerated
     */
    private Integer matchedSellerLeg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trader_leg.reject_reason
     *
     * @mbggenerated
     */
    private String rejectReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.inter_v_num
     *
     * @return the value of trader_leg.inter_v_num
     *
     * @mbggenerated
     */
    public Integer getInterVNum() {
        return interVNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.inter_v_num
     *
     * @param interVNum the value for trader_leg.inter_v_num
     *
     * @mbggenerated
     */
    public void setInterVNum(Integer interVNum) {
        this.interVNum = interVNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.status
     *
     * @return the value of trader_leg.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.status
     *
     * @param status the value for trader_leg.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.reject_code
     *
     * @return the value of trader_leg.reject_code
     *
     * @mbggenerated
     */
    public String getRejectCode() {
        return rejectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.reject_code
     *
     * @param rejectCode the value for trader_leg.reject_code
     *
     * @mbggenerated
     */
    public void setRejectCode(String rejectCode) {
        this.rejectCode = rejectCode == null ? null : rejectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.t_id
     *
     * @return the value of trader_leg.t_id
     *
     * @mbggenerated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.t_id
     *
     * @param tId the value for trader_leg.t_id
     *
     * @mbggenerated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.s_id
     *
     * @return the value of trader_leg.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.s_id
     *
     * @param sId the value for trader_leg.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.cusip
     *
     * @return the value of trader_leg.cusip
     *
     * @mbggenerated
     */
    public String getCusip() {
        return cusip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.cusip
     *
     * @param cusip the value for trader_leg.cusip
     *
     * @mbggenerated
     */
    public void setCusip(String cusip) {
        this.cusip = cusip == null ? null : cusip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.price
     *
     * @return the value of trader_leg.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.price
     *
     * @param price the value for trader_leg.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.notional_amount
     *
     * @return the value of trader_leg.notional_amount
     *
     * @mbggenerated
     */
    public Integer getNotionalAmount() {
        return notionalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.notional_amount
     *
     * @param notionalAmount the value for trader_leg.notional_amount
     *
     * @mbggenerated
     */
    public void setNotionalAmount(Integer notionalAmount) {
        this.notionalAmount = notionalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.matched_seller_leg
     *
     * @return the value of trader_leg.matched_seller_leg
     *
     * @mbggenerated
     */
    public Integer getMatchedSellerLeg() {
        return matchedSellerLeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.matched_seller_leg
     *
     * @param matchedSellerLeg the value for trader_leg.matched_seller_leg
     *
     * @mbggenerated
     */
    public void setMatchedSellerLeg(Integer matchedSellerLeg) {
        this.matchedSellerLeg = matchedSellerLeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trader_leg.reject_reason
     *
     * @return the value of trader_leg.reject_reason
     *
     * @mbggenerated
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trader_leg.reject_reason
     *
     * @param rejectReason the value for trader_leg.reject_reason
     *
     * @mbggenerated
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason == null ? null : rejectReason.trim();
    }
}